logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    cloud:
        config:
            import-check:
                enabled: false
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: pscale_pw_GlBtIRuxB9Mq9EJI8r6a4WqXEnPvdxQy8LnbCxvyTsy
        url: jdbc:mysql://aws.connect.psdb.cloud/autodeluxe?sslMode=VERIFY_IDENTITY
        username: gwcy3cicdeo3ioite10r

#        password: admin
#        url: jdbc:mysql://localhost:3306/auto_delux?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimeZone=UTC
#        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    server:
        port: 8080